# Customize to your needs...
if [[ -z $TMUXX  ]]; then
  export PATH=/usr/local/sbin:$PATH
  export PATH=/opt/local/sbin:/opt/local/bin:$PATH
  export PATH=$HOME/node_modules/.bin:$PATH
  export PATH=$HOME/.local/bin:$PATH
  export PATH=$HOME/bin:$PATH
fi

if [ -d $HOME/Library/Android/sdk ]; then
  export ANDROID_HOME=$HOME/Library/Android/sdk
  export ANDROID_SDK_HOME=$ANDROID_HOME
  export PATH=$ANDROID_HOME:$ANDROID_HOME/platform-tools/:$PATH
fi

if which yarn > /dev/null; then
  export PATH="`yarn global bin`:$PATH"
  export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
fi
export VISUAL=nvim
export EDITOR=nvim
export GIT_EDITOR=nvim
alias ssh='TERM=xterm-256color ssh'

for zsh_source in ~/.config/zsh/config.d/*.zsh; do
  source $zsh_source
done
