# Customize to your needs...
if [[ -z $TMUXX  ]]; then
  export PATH=/usr/local/sbin:$PATH
  export PATH=/opt/local/sbin:/opt/local/bin:$PATH
  export PATH=$HOME/node_modules/.bin:$PATH
  export PATH=$HOME/.local/bin:$PATH
  export PATH=$HOME/bin:$PATH
fi

if which yarn > /dev/null; then
  export PATH="`yarn global bin`:$PATH"
fi
export VISUAL=nvim
export EDITOR=nvim
export GIT_EDITOR=nvim
alias ssh='TERM=xterm-256color ssh'

for zsh_source in ~/.config/zsh/config.d/*.zsh; do
  source $zsh_source
done
